
spotify {
    clientId = "99dedc035fd44247a60054585bae8cb8"

    clientSecret = ${SPOTIFY_CLIENT_SECRET}

    redirectUri = "http://127.0.0.1:8080/callback"
}

songDatabase {
    path = "src/main/resources/dataset.csv"
}

playedSongs {
    path = "src/main/resources/playedSongs.csv"
}